"""delete_address

Revision ID: 33a58a00026d
Revises: 40a692c1831f
Create Date: 2020-05-28 15:26:09.806961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33a58a00026d'
down_revision = '40a692c1831f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ods_p1_Post', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ods_p1_Post', sa.Column('address', mysql.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
