"""add1

Revision ID: 13ee2b9c6f28
Revises: 2faec971c53b
Create Date: 2020-05-27 20:18:42.270200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ee2b9c6f28'
down_revision = '2faec971c53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('add1', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'add1')
    # ### end Alembic commands ###
